// Based on ENTSO-E codelist 92 Release Date: 2025-01-13
// https://www.entsoe.eu/publications/electronic-data-interchange-edi-library/

namespace EnergyReferenceData;

/// <summary>
/// The identification of the type of fuel.
/// </summary>
/// <remarks>
/// ET0051
/// </remarks>
public enum FuelType
{
    /// <summary>
    /// Unspecified
    /// </summary>
    /// <remarks>
    /// Fuel that cannot be associated with any of available fuel codes.
    /// </remarks>
    A01,

    /// <summary>
    /// Renewable solid unspecified
    /// </summary>
    /// <remarks>
    /// Fuel produced in a solid form from renewable resources that cannot be associated with any of available renewable solid fuel codes.
    /// </remarks>
    A02,

    /// <summary>
    /// Renewable solid municipal waste
    /// </summary>
    /// <remarks>
    /// Solid waste of biological material produced by households, hospitals and the tertiary sector (in general all waste that resembles household waste).
    /// </remarks>
    A03,

    /// <summary>
    /// Renewable solid industrial and commercial waste
    /// </summary>
    /// <remarks>
    /// Solid waste generated by businesses, production units, bureaus and offices.
    /// </remarks>
    A04,

    /// <summary>
    /// Renewable solid wood
    /// </summary>
    /// <remarks>
    /// Solid wood energy resource.
    /// </remarks>
    A05,

    /// <summary>
    /// Renewable solid animal fats
    /// </summary>
    /// <remarks>
    /// Solid animal fats energy resource.
    /// </remarks>
    A06,

    /// <summary>
    /// Renewable solid biomass from agriculture
    /// </summary>
    /// <remarks>
    /// Solid by-products and residues from agriculture.
    /// </remarks>
    A07,

    /// <summary>
    /// Renewable liquid unspecified
    /// </summary>
    /// <remarks>
    /// Fuel produced in form of liquid from renewable resources that cannot be associated with any of available renewable liquid fuel codes.
    /// </remarks>
    A08,

    /// <summary>
    /// Renewable liquid municipal biodegradable waste
    /// </summary>
    /// <remarks>
    /// Liquid municipal waste capable of undergoing anaerobic or aerobic decomposition.
    /// </remarks>
    A09,

    /// <summary>
    /// Renewable liquid black liquor
    /// </summary>
    /// <remarks>
    /// Alkaline-spent liquor obtained from the digesters during the production of sulphate or soda pulp.
    /// </remarks>
    A10,

    /// <summary>
    /// Renewable liquid pure plant oil
    /// </summary>
    /// <remarks>
    /// Oil produced from plants, mainly from rapeseed and sunflower crops.
    /// </remarks>
    A11,

    /// <summary>
    /// Renewable liquid waste plant oil
    /// </summary>
    /// <remarks>
    /// Oil produced from plants that is no longer usable for its originally intended purpose.
    /// </remarks>
    A12,

    /// <summary>
    /// Renewable liquid refined vegetable oil
    /// </summary>
    /// <remarks>
    /// Oil produced from plants and transformed into fuel by refining process (hydrocracking or hydrogenation).
    /// </remarks>
    A13,

    /// <summary>
    /// Renewable gaseous unspecified
    /// </summary>
    /// <remarks>
    /// Fuel produced in form of gas from renewable resources that cannot be associated with any of available renewable gaseous fuel codes.
    /// </remarks>
    A14,

    /// <summary>
    /// Renewable gaseous landfill gas
    /// </summary>
    /// <remarks>
    /// Gas produced by digestion of land filled waste.
    /// </remarks>
    A15,

    /// <summary>
    /// Renewable gaseous sewage gas
    /// </summary>
    /// <remarks>
    /// Gas produced from the anaerobic fermentation of sewage sludge.
    /// </remarks>
    A16,

    /// <summary>
    /// Renewable gaseous agricultural gas
    /// </summary>
    /// <remarks>
    /// Gas produced from agricultural processes.
    /// </remarks>
    A17,

    /// <summary>
    /// Renewable gaseous gas from organic waste digestion
    /// </summary>
    /// <remarks>
    /// Gas produced by anaerobic digestion process from organic waste.
    /// </remarks>
    A18,

    /// <summary>
    /// Renewable gaseous process gas
    /// </summary>
    /// <remarks>
    /// Gas produced by an industrial process as a consequence.
    /// </remarks>
    A19,

    /// <summary>
    /// Renewable gaseous other biogenic sources
    /// </summary>
    /// <remarks>
    /// Gas produced by form of biogenic resource transformation that cannot be associated with any of available renewable gaseous fuel codes that use biogenic energy resource.
    /// </remarks>
    A20,

    /// <summary>
    /// Renewable heating and cooling solar
    /// </summary>
    /// <remarks>
    /// Sunlight energy source.
    /// </remarks>
    A21,

    /// <summary>
    /// Renewable heating and cooling geothermal
    /// </summary>
    /// <remarks>
    /// Geothermal energy source.
    /// </remarks>
    A22,

    /// <summary>
    /// Renewable heating and cooling aerothermal
    /// </summary>
    /// <remarks>
    /// Thermal energy obtained from air.
    /// </remarks>
    A23,

    /// <summary>
    /// Renewable heating and cooling hydrothermal
    /// </summary>
    /// <remarks>
    /// Thermal energy obtained from large body of water.
    /// </remarks>
    A24,

    /// <summary>
    /// Renewable heating and cooling process heat
    /// </summary>
    /// <remarks>
    /// Thermal energy obtained from process heat.
    /// </remarks>
    A25,

    /// <summary>
    /// Renewable mechanical unspecified
    /// </summary>
    /// <remarks>
    /// Energy from renewable resource transformed into mechanical energy that cannot be associated with any of available renewable mechanical fuel codes.
    /// </remarks>
    A26,

    /// <summary>
    /// Renewable mechanical wind
    /// </summary>
    /// <remarks>
    /// Kinetic energy of wind transformed into mechanical energy.
    /// </remarks>
    A27,

    /// <summary>
    /// Renewable mechanical hydro and marine
    /// </summary>
    /// <remarks>
    /// Falling or flowing water energy or energy derived from tidal movement, wave motion or ocean current.
    /// </remarks>
    A28,

    /// <summary>
    /// Fossil unspecified
    /// </summary>
    /// <remarks>
    /// Unspecified fossil energy source.
    /// </remarks>
    A29,

    /// <summary>
    /// Fossil solid unspecified
    /// </summary>
    /// <remarks>
    /// Unspecified fossil solid energy source.
    /// </remarks>
    A30,

    /// <summary>
    /// Fossil solid hard coal
    /// </summary>
    /// <remarks>
    /// Hard coal solid fossil energy source. This includes Anthracite, Bituminous coal, Coking coal, Coke-oven coke and Lignite coke.
    /// </remarks>
    A31,

    /// <summary>
    /// Fossil solid brown coal
    /// </summary>
    /// <remarks>
    /// Brown coal solid fossil energy source. This includes Sub-bituminous coal, Lignite, Brown coal briquette and Peat briquette.
    /// </remarks>
    A32,

    /// <summary>
    /// Fossil solid peat
    /// </summary>
    /// <remarks>
    /// Solid fossil peat energy source.
    /// </remarks>
    A33,

    /// <summary>
    /// Fossil solid municipal waste
    /// </summary>
    /// <remarks>
    /// Solid fossil municipal waste energy source.
    /// </remarks>
    A34,

    /// <summary>
    /// Fossil solid industrial and commercial waste
    /// </summary>
    /// <remarks>
    /// Solid fossil industrial and commercial waste energy source.
    /// </remarks>
    A35,

    /// <summary>
    /// Fossil liquid unspecified
    /// </summary>
    /// <remarks>
    /// Unspecified fossil liquid energy source.
    /// </remarks>
    A36,

    /// <summary>
    /// Fossil liquid crude oil
    /// </summary>
    /// <remarks>
    /// Liquid crude oil fossil energy source. This includes shale oil or other types.
    /// </remarks>
    A37,

    /// <summary>
    /// Fossil liquid natural gas liquids (NGL)
    /// </summary>
    /// <remarks>
    /// Liquid natural gas liquids (NGL) fossil energy source.
    /// </remarks>
    A38,

    /// <summary>
    /// Fossil liquid petroleum products
    /// </summary>
    /// <remarks>
    /// Liquid petroleum products energy source. This includes Ethane,Naphtha, Aviation gasoline , Motor gasoline, Aviation turbine fuel,Other kerosene,Gas/diesel oil , Fuel oil, low sulphur ,Fuel oil, high sulphur ,Liquid Petroleum Gas , Orimulsion , Bitumen ,Lubricants ,Petroleum coke , Refinery Feedstock.
    /// </remarks>
    A39,

    /// <summary>
    /// Fossil gaseous unspecified
    /// </summary>
    /// <remarks>
    /// Unspecified fossil gaseous  energy source.
    /// </remarks>
    A40,

    /// <summary>
    /// Fossil gaseous natural gas
    /// </summary>
    /// <remarks>
    /// Fossil gaseous natural gas energy source.
    /// </remarks>
    A41,

    /// <summary>
    /// Fossil gaseous coal-derived gas
    /// </summary>
    /// <remarks>
    /// Fossil gaseous coal-derived gas energy source. This includes Blast furnace gas,Coke-oven gas or other types.
    /// </remarks>
    A42,

    /// <summary>
    /// Fossil gaseous petroleum products
    /// </summary>
    /// <remarks>
    /// Fossil gaseous petroleum products energy  source. This includes Propane, Butane, Refinery gas, Chemical waste gas or other types.
    /// </remarks>
    A43,

    /// <summary>
    /// Fossil gaseous municipal gas plant
    /// </summary>
    /// <remarks>
    /// Fossil gaseous municipal gas plant energy source. 
    /// </remarks>
    A44,

    /// <summary>
    /// Fossil gaseous process gas
    /// </summary>
    /// <remarks>
    /// Fossil gaseous process gas energy source. This includes Carbon monoxide,	/// Methane , Hydrogen (fossil sourced) ,Phosphor gas ,Oxy gas and other types.
    /// </remarks>
    A45,

    /// <summary>
    /// Fossil heat unspecified
    /// </summary>
    /// <remarks>
    /// Unspecified fossil heat energy source.
    /// </remarks>
    A46,

    /// <summary>
    /// Fossil heat process heat
    /// </summary>
    /// <remarks>
    /// Fossil process heat energy source.
    /// </remarks>
    A47,

    /// <summary>
    /// Nuclear solid radioactive fuel
    /// </summary>
    /// <remarks>
    /// Solid Nuclear  radioactive energy source. This includes UOX, AGR, MOX or other types.
    /// </remarks>
    A48,

    /// <summary>
    /// Gas synthesis unspecified
    /// </summary>
    /// <remarks>
    /// Unspecified gas synthesis energy source.
    /// </remarks>
    A49,

    /// <summary>
    /// Gas synthesis furnace gas
    /// </summary>
    /// <remarks>
    /// Gas synthesis from furnace gas energy source.
    /// </remarks>
    A50,

    /// <summary>
    /// Waste heat and cold unspecified
    /// </summary>
    /// <remarks>
    /// Unspecified Waste heat and cold energy source.
    /// </remarks>
    A51,

    /// <summary>
    /// Waste heat and cold By-product in industrial installation
    /// </summary>
    /// <remarks>
    /// Waste heat and cold from by-product in industrial installation energy source.
    /// </remarks>
    A52,

    /// <summary>
    /// Waste heat and cold By-product in power generation
    /// </summary>
    /// <remarks>
    /// Waste heat and cold from by-product in power generation energy source.
    /// </remarks>
    A53,

    /// <summary>
    /// Waste heat and cold By-product in tertiary sector
    /// </summary>
    /// <remarks>
    /// Waste heat and cold from by-product in tertiary sector energy  source.
    /// </remarks>
    A54,

    /// <summary>
    /// Hydrogen
    /// </summary>
    /// <remarks>
    /// Hydrogen energy source.
    /// </remarks>
    A55
}

